<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/14.0.2">
    <Target Name="GetTagVersion" BeforeTargets="BeforeBuild;CoreCompile">
        <Exec Command="git describe --tags --abbrev=0 --exclude latest" ConsoleToMSBuild="true" StandardOutputImportance="low">
            <Output TaskParameter="ConsoleOutput" ItemName="TagVersion" />
        </Exec>
        <Exec Command="git rev-list --count origin/main" ConsoleToMSBuild="true" StandardOutputImportance="low">
            <Output TaskParameter="ConsoleOutput" ItemName="CommitCount" />
        </Exec>

        <PropertyGroup>
            <Version>@(TagVersion).@(CommitCount)</Version>
        </PropertyGroup>
    </Target>

    <PropertyGroup>
        <PackageProjectUrl>https://github.com/zodiia/BetterAchievements</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="BetterAchievements.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\layout.jsonc">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="DalamudPackager" Version="14.0.2" />
        <PackageReference Include="Dapper" Version="2.1.86" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    </ItemGroup>
</Project>
