name: Build latest on main

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: BetterAchievements

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Install .NET
        uses: https://github.com/actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Setup Dalamud
        uses: https://github.com/Blooym/setup-dalamud@v1
        with:
          branch: release

      - name: Generate testing repo JSON and get current commit count
        id: eval-vars
        shell: bash
        run: |
          eval "echo \"$(sed 's/"/\\"/g' testing-repo-template.json)\"" > testing-repo.json
          echo "commitcount=$(git rev-list --count main)" >> "$GITHUB_OUTPUT"

      - name: Correctly set .csproj Version field
        uses: https://github.com/vers-one/dotnet-project-version-updater@v1.8
        with:
          file: "**/*.csproj"
          version: "*.*.*.${{ steps.eval-vars.outputs.commitcount }}"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Stage release files
        run: |
          mkdir -p dist/forgejo-release
          cp BetterAchievements/bin/x64/Release/BetterAchievements/* dist/forgejo-release/
          cp testing-repo.json dist/forgejo-release/

      - name: Update Latest Release
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: latest
          release-notes: "Latest build from main"
          release-dir: dist/forgejo-release/
          override: true
          prerelease: true
