name: Build latest on main

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  build:
    runs-on: ubuntu-latest

    # if running on a release event, only run it if it's not a prerelease
    #   (otherwise we're in for an infinite loop! not yay)
    if: ${{ github.event_name == 'push' || !github.event.release.prerelease }}

    env:
      Solution_Name: Recollection

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Install .NET
        uses: https://github.com/actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Setup Dalamud
        uses: https://github.com/Blooym/setup-dalamud@v1
        with:
          branch: release

      - name: Generate testing repo JSON
        id: eval-vars
        shell: bash
        run: |
          eval "echo \"$(sed 's/"/\\"/g' testing-repo-template.json)\"" > testing-repo.json

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Stage release files
        run: |
          mkdir -p dist/forgejo-release
          cp Recollection/bin/x64/Release/Recollection/* dist/forgejo-release/
          cp testing-repo.json dist/forgejo-release/

      - name: Update Latest Release
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          token: ${{ secrets.RELEASE_TOKEN }}
          repo: xiv/Recollection
          url: https://git.zodiia.moe
          tag: latest
          release-notes: "Latest build from main"
          release-dir: dist/forgejo-release/
          override: true
          prerelease: true
