name: Build latest on main

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-2022

    env:
      Solution_Name: BetterAchievements

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Generate testing repo JSON
      run: |
        eval "echo \"$(sed 's/"/\\"/g' testing-repo-template.json)\"" > testing-repo.json

    - name: Update Latest Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          BetterAchievements\bin\x64\Release\BetterAchievements\*
          testing-repo.json
        tag_name: latest
        name: "Latest Build"
        prerelease: true
        token: ${{ secrets.RELEASE_TOKEN }}
